package com.example.springboot_postgres.service;

import com.example.springboot_postgres.dto.UserRequest;
import com.example.springboot_postgres.model.AppUser;
import com.example.springboot_postgres.repository.AppUserRepository;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.http.HttpStatus;
import org.springframework.web.server.ResponseStatusException;

import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/** Unit tests for {@link AppService}; the repository is mocked. */
@ExtendWith(MockitoExtension.class)
class AppServiceTest {

    @Mock
    AppUserRepository userRepository;

    @InjectMocks
    AppService service;

    private AppUser existingUser() {
        AppUser user = new AppUser();
        user.setId(1L);
        user.setUsername("john_doe");
        user.setEmail("john@gmail.com");
        when(userRepository.findById(1L)).thenReturn(Optional.of(user));
        return user;
    }

    @Test
    void createUser_buildsUserFromRequest() {
        when(userRepository.save(any(AppUser.class))).thenAnswer(inv -> inv.getArgument(0));

        AppUser created = service.createUser(new UserRequest("new_user", "new@gmail.com"));

        assertNull(created.getId());  // generated by the database on insert
        assertEquals("new_user", created.getUsername());
        assertEquals("new@gmail.com", created.getEmail());
        assertNull(created.getProfile());
        assertTrue(created.getPosts().isEmpty());
        assertTrue(created.getRoles().isEmpty());
    }

    @Test
    void createUser_withoutUsername_throws400() {
        ResponseStatusException ex = assertThrows(ResponseStatusException.class,
                () -> service.createUser(new UserRequest(null, "x@gmail.com")));
        assertEquals(HttpStatus.BAD_REQUEST, ex.getStatusCode());
        verify(userRepository, never()).save(any());
    }

    @Test
    void updateUser_appliesOnlyNonNullFields() {
        AppUser user = existingUser();
        when(userRepository.save(user)).thenReturn(user);

        service.updateUser(1L, new UserRequest(null, "updated@gmail.com"));

        assertEquals("john_doe", user.getUsername());
        assertEquals("updated@gmail.com", user.getEmail());
    }

    @Test
    void updateUser_whenMissing_returnsEmpty() {
        when(userRepository.findById(999L)).thenReturn(Optional.empty());

        assertTrue(service.updateUser(999L, new UserRequest("x", null)).isEmpty());
    }

    @Test
    void updateUser_withBlankUsername_throws400() {
        ResponseStatusException ex = assertThrows(ResponseStatusException.class,
                () -> service.updateUser(1L, new UserRequest(" ", null)));
        assertEquals(HttpStatus.BAD_REQUEST, ex.getStatusCode());
    }
}
