package com.example.springboot_postgres.service;

import com.example.springboot_postgres.dto.PostRequest;
import com.example.springboot_postgres.model.AppUser;
import com.example.springboot_postgres.model.Post;
import com.example.springboot_postgres.repository.AppUserRepository;
import com.example.springboot_postgres.repository.PostRepository;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.http.HttpStatus;
import org.springframework.web.server.ResponseStatusException;

import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/** Unit tests for {@link PostService}; repositories are mocked. */
@ExtendWith(MockitoExtension.class)
class PostServiceTest {

    @Mock
    PostRepository postRepository;

    @Mock
    AppUserRepository userRepository;

    @InjectMocks
    PostService service;

    @Test
    void createPost_buildsPostLinkedToUser() {
        AppUser userRef = new AppUser();
        when(userRepository.existsById(1L)).thenReturn(true);
        when(userRepository.getReferenceById(1L)).thenReturn(userRef);
        when(postRepository.save(any(Post.class))).thenAnswer(inv -> inv.getArgument(0));

        Post result = service.createPost(1L, new PostRequest("hello"));

        assertNull(result.getId());  // generated by the database on insert
        assertEquals("hello", result.getContent());
        // Post owns the many-to-one, so the link is set on the post.
        assertSame(userRef, result.getAppUser());
    }

    @Test
    void createPost_whenUserMissing_throws404() {
        when(userRepository.existsById(999L)).thenReturn(false);

        ResponseStatusException ex = assertThrows(ResponseStatusException.class,
                () -> service.createPost(999L, new PostRequest("hello")));
        assertEquals(HttpStatus.NOT_FOUND, ex.getStatusCode());
        verify(postRepository, never()).save(any());
    }

    @Test
    void createPost_withoutContent_throws400() {
        ResponseStatusException ex = assertThrows(ResponseStatusException.class,
                () -> service.createPost(1L, new PostRequest(null)));
        assertEquals(HttpStatus.BAD_REQUEST, ex.getStatusCode());
        verify(postRepository, never()).save(any());
    }

    @Test
    void updatePost_withBlankContent_throws400() {
        ResponseStatusException ex = assertThrows(ResponseStatusException.class,
                () -> service.updatePost(5L, new PostRequest("  ")));
        assertEquals(HttpStatus.BAD_REQUEST, ex.getStatusCode());
    }

    @Test
    void getPostsByUser_whenUserMissing_throws404() {
        when(userRepository.existsById(999L)).thenReturn(false);

        assertThrows(ResponseStatusException.class, () -> service.getPostsByUser(999L));
        verify(postRepository, never()).findByAppUserId(any());
    }

    @Test
    void updatePost_ignoresNullContent() {
        Post existing = new Post();
        existing.setContent("original");
        when(postRepository.findById(5L)).thenReturn(Optional.of(existing));

        service.updatePost(5L, new PostRequest(null));

        assertEquals("original", existing.getContent());
    }

    @Test
    void deletePost_whenMissing_throws404() {
        when(postRepository.existsById(999L)).thenReturn(false);

        assertThrows(ResponseStatusException.class, () -> service.deletePost(999L));
        verify(postRepository, never()).deleteById(any());
    }
}
